I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 628, in script
    show ollie ghost
Exception: Image 'ollie' does not accept attributes 'ghost'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 628, in script
    show ollie ghost
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "/Applications/renpy-7.4.11-sdk/renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Applications/renpy-7.4.11-sdk/renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "/Applications/renpy-7.4.11-sdk/renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "/Applications/renpy-7.4.11-sdk/renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'ollie' does not accept attributes 'ghost'.

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
APEX and the Great Flame War 1.0
Mon Jan 24 18:14:24 2022
